/*

Problem: https://onlinejudge.org/index.php?option=com_onlinejudge&Itemid=8&page=show_problem&problem=2407

Ignacio Osorio
Cocobio2

Generated by Ignacio Osorio Wallace


*/




int main() {
	return 0;
}
