/*

Problem: https://onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=2613

Ignacio Osorio
Cocobio2

Generated by Ignacio Osorio Wallace


*/

#include <iostream>
#include <vector>

using namespace std;

int main() {
	unsigned char N,x,T,K;

	while (cin >> N >> x >> T >> K && 
		  N!=0 && x!=0 && T!=0 && K!=0) {
		
		
	}

	return 0;
}
