/*

Problem: https://onlinejudge.org/index.php?option=onlinejudge&Itemid=8&page=show_problem&problem=3362

Ignacio Osorio
Cocobio2

Generated by Ignacio Osorio Wallace


*/




int main() {
	return 0;
}
