/*

Problem: https://onlinejudge.org/index.php?option=onlinejudge&page=show_problem&problem=565

Ignacio Osorio
Cocobio2

Generated by Ignacio Osorio Wallace


*/
#include <iostream>
#include <string>
#include <sstream>
#include <vector>
#include <cstdlib>
#include <algorithm>

using namespace std;

unsigned** create_dynamic_programming_table(unsigned x, unsigned y) {
	unsigned* data = (unsigned*) malloc(x*y*sizeof(unsigned));
	unsigned** table = (unsigned**) malloc(y*sizeof(unsigned*));

	for (int i=0; i<y; i++)
		table[i] = data+i*x;

	return table;
}

void clear_table(unsigned ** table) {
	free(table[0]);
	free(table);
}

int main() {
	string line;

	while (getline(cin, line) && line.size() != 0) {
		stringstream s(line);
		// cout << "input: " << line << endl;

		unsigned tape_length;
		unsigned track_n;
		vector<unsigned> track_times;
		unsigned tmp;

		s >> tape_length;
		s >> track_n;

		while (s >> tmp) track_times.push_back(tmp);

		// Create a table for memoization
		unsigned ** table = create_dynamic_programming_table(tape_length+1, track_times.size()+1);

		// Base case for dynamic programming solution
		for (int i=0; i<=tape_length; i++) table[0][i] = i;

		// dynamic programming approach
		for (unsigned i=1; i<=track_times.size(); i++) {
			for (unsigned j=0; j<=tape_length; j++) {
				unsigned included;
				unsigned not_included = table[i-1][j]; 
				unsigned tape_j = j-track_times[i-1];
				
				if (tape_j > tape_length) { // it gets cast to a unsigned so it cant be check if is less than 0
					table[i][j] = not_included;
				}
				else {
					included = table[i-1][tape_j];
					table[i][j] = min(included, not_included);
				}
			}
		}

		// Print results
		cout << "sum:" << tape_length-table[track_times.size()][tape_length];
		cout << endl;
		// cout << "tabla:" << endl;
		// for (int i=0; i<=track_times.size(); i++) {
		// 	for (int j=0; j<=tape_length; j++)
		// 		cout << table[i][j] << " ";
		// 	cout << endl;
		// }

		// cout << endl;

		// Clear containers
		clear_table(table);
		track_times.clear();
	}

	return 0;
}
